//! TRU Language Compiler — transpiles TRU AST to optimised Rust source.

use crate::tru_lang::ast::*;

// ─── Error ────────────────────────────────────────────────────────────────────

#[derive(Debug)]
pub struct CompileError(pub String);

impl std::fmt::Display for CompileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "[CompileError] {}", self.0)
    }
}

type CResult<T = String> = Result<T, CompileError>;

// ─── Compiler ─────────────────────────────────────────────────────────────────

pub struct Compiler {
    indent: usize,
    output: String,
}

impl Compiler {
    pub fn new() -> Self {
        Self { indent: 0, output: String::new() }
    }

    /// Compile a full Program to a Rust source string.
    pub fn compile(program: &Program) -> CResult {
        let mut c = Compiler::new();
        c.emit_header();
        for stmt in &program.stmts {
            let s = c.stmt(stmt)?;
            c.output.push_str(&s);
            c.output.push('\n');
        }
        Ok(c.output)
    }

    // ── header ────────────────────────────────────────────────────────────────

    fn emit_header(&mut self) {
        self.output.push_str("// Auto-generated by tru_id compiler\n");
        self.output.push_str("#![allow(unused, non_snake_case, dead_code)]\n");
        self.output.push_str("use tru_id_core::prelude::*;\n\n");
    }

    // ── indent helpers ────────────────────────────────────────────────────────

    fn ind(&self) -> String {
        "    ".repeat(self.indent)
    }

    fn push(&mut self) { self.indent += 1; }
    fn pop(&mut self)  { if self.indent > 0 { self.indent -= 1; } }

    // ── statements ────────────────────────────────────────────────────────────

    fn stmt(&mut self, s: &Stmt) -> CResult {
        match s {
            Stmt::Let(l)          => self.let_stmt(l),
            Stmt::Fn(f)           => self.fn_decl(f),
            Stmt::Struct(s)       => self.struct_decl(s),
            Stmt::Enum(e)         => self.enum_decl(e),
            Stmt::Impl(i)         => self.impl_block(i),
            Stmt::Trait(t)        => self.trait_decl(t),
            Stmt::Return(e, _)    => {
                let v = if let Some(e) = e { self.expr(e)? } else { "()".to_string() };
                Ok(format!("{}return {};", self.ind(), v))
            }
            Stmt::If(i)           => self.if_stmt(i),
            Stmt::While(w)        => self.while_stmt(w),
            Stmt::For(f)          => self.for_stmt(f),
            Stmt::Break(_)        => Ok(format!("{}break;", self.ind())),
            Stmt::Continue(_)     => Ok(format!("{}continue;", self.ind())),
            Stmt::Expr(e)         => Ok(format!("{}{};", self.ind(), self.expr(e)?)),
            Stmt::Block(stmts, _) => self.block_stmts(stmts),
            Stmt::Use(path, _)    => {
                let segs = path.segments.join("::");
                Ok(format!("{}use {};", self.ind(), segs))
            }
            Stmt::Mod(name, stmts, _) => {
                self.push();
                let body = stmts.iter().map(|s| self.stmt(s)).collect::<CResult<Vec<_>>>()?.join("\n");
                self.pop();
                Ok(format!("{}mod {} {{\n{}\n{}}}", self.ind(), name, body, self.ind()))
            }
        }
    }

    fn let_stmt(&mut self, l: &LetStmt) -> CResult {
        let mut_kw = if l.mutable { "mut " } else { "" };
        let ty_ann = if let Some(ty) = &l.ty {
            format!(": {}", self.type_expr(ty))
        } else { String::new() };
        let init = if let Some(e) = &l.value {
            format!(" = {}", self.expr(e)?)
        } else { String::new() };
        Ok(format!("{}let {}{}{}{};", self.ind(), mut_kw, l.name, ty_ann, init))
    }

    fn fn_decl(&mut self, f: &FnDecl) -> CResult {
        let vis = if f.is_pub { "pub " } else { "" };
        let params = f.params.iter().map(|p| {
            format!("{}: {}", p.name, self.type_expr(&p.ty))
        }).collect::<Vec<_>>().join(", ");
        let ret = if let Some(ty) = &f.ret_ty {
            format!(" -> {}", self.type_expr(ty))
        } else { String::new() };
        let body = self.block_body(&f.body)?;
        Ok(format!("{}{}fn {}({}){}{}",
            self.ind(), vis, f.name, params, ret, body))
    }

    fn struct_decl(&mut self, s: &StructDecl) -> CResult {
        let vis = if s.is_pub { "pub " } else { "" };
        self.push();
        let fields = s.fields.iter().map(|f| {
            let fvis = if f.is_pub { "pub " } else { "" };
            format!("{}{}{}: {},", self.ind(), fvis, f.name, self.type_expr(&f.ty))
        }).collect::<Vec<_>>().join("\n");
        self.pop();
        Ok(format!("{}{}struct {} {{\n{}\n{}}}", self.ind(), vis, s.name, fields, self.ind()))
    }

    fn enum_decl(&mut self, e: &EnumDecl) -> CResult {
        let vis = if e.is_pub { "pub " } else { "" };
        self.push();
        let variants = e.variants.iter().map(|v| {
            if v.fields.is_empty() {
                format!("{}{},", self.ind(), v.name)
            } else {
                let tys = v.fields.iter().map(|t| self.type_expr(t)).collect::<Vec<_>>().join(", ");
                format!("{}{}({}),", self.ind(), v.name, tys)
            }
        }).collect::<Vec<_>>().join("\n");
        self.pop();
        Ok(format!("{}{}enum {} {{\n{}\n{}}}", self.ind(), vis, e.name, variants, self.ind()))
    }

    fn impl_block(&mut self, i: &ImplBlock) -> CResult {
        let for_part = if let Some(tr) = &i.trait_name {
            format!("{} for ", tr)
        } else { String::new() };
        self.push();
        let methods = i.methods.iter()
            .map(|m| self.fn_decl(m))
            .collect::<CResult<Vec<_>>>()?
            .join("\n\n");
        self.pop();
        Ok(format!("{}impl {}{} {{\n{}\n{}}}", self.ind(), for_part, i.ty, methods, self.ind()))
    }

    fn trait_decl(&mut self, t: &TraitDecl) -> CResult {
        let vis = if t.is_pub { "pub " } else { "" };
        self.push();
        let methods = t.methods.iter().map(|m| {
            let params = m.params.iter().map(|p| format!("{}: {}", p.name, self.type_expr(&p.ty))).collect::<Vec<_>>().join(", ");
            let ret = if let Some(ty) = &m.ret_ty { format!(" -> {}", self.type_expr(ty)) } else { String::new() };
            format!("{}fn {}({}){};", self.ind(), m.name, params, ret)
        }).collect::<Vec<_>>().join("\n");
        self.pop();
        Ok(format!("{}{}trait {} {{\n{}\n{}}}", self.ind(), vis, t.name, methods, self.ind()))
    }

    fn if_stmt(&mut self, i: &IfStmt) -> CResult {
        let cond = self.expr(&i.cond)?;
        let then = self.block_body(&i.then_block)?;
        let else_part = if let Some(else_b) = &i.else_block {
            format!(" else{}", self.block_body(else_b)?)
        } else { String::new() };
        Ok(format!("{}if {}{}{}", self.ind(), cond, then, else_part))
    }

    fn while_stmt(&mut self, w: &WhileStmt) -> CResult {
        let cond = self.expr(&w.cond)?;
        let body = self.block_body(&w.body)?;
        Ok(format!("{}while {}{}", self.ind(), cond, body))
    }

    fn for_stmt(&mut self, f: &ForStmt) -> CResult {
        let iter = self.expr(&f.iter)?;
        let body = self.block_body(&f.body)?;
        Ok(format!("{}for {} in {}{}", self.ind(), f.var, iter, body))
    }

    fn block_body(&mut self, stmts: &[Stmt]) -> CResult {
        self.push();
        let body = stmts.iter().map(|s| self.stmt(s)).collect::<CResult<Vec<_>>>()?.join("\n");
        self.pop();
        Ok(format!(" {{\n{}\n{}}}", body, self.ind()))
    }

    fn block_stmts(&mut self, stmts: &[Stmt]) -> CResult {
        self.push();
        let body = stmts.iter().map(|s| self.stmt(s)).collect::<CResult<Vec<_>>>()?.join("\n");
        self.pop();
        Ok(format!("{}{{\n{}\n{}}}", self.ind(), body, self.ind()))
    }

    // ── expressions ───────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> CResult {
        match e {
            Expr::Int(n, _)    => Ok(n.to_string()),
            Expr::Float(f, _)  => Ok(format!("{}_f64", f)),
            Expr::Str(s, _)    => Ok(format!("\"{}\".to_string()", s.escape_default())),
            Expr::Bool(b, _)   => Ok(b.to_string()),
            Expr::Nil(_)       => Ok("None".to_string()),
            Expr::Ident(n, _)  => Ok(n.clone()),

            Expr::Array(items, _) => {
                let vs = items.iter().map(|e| self.expr(e)).collect::<CResult<Vec<_>>>()?.join(", ");
                Ok(format!("vec![{}]", vs))
            }

            Expr::Tuple(items, _) => {
                let vs = items.iter().map(|e| self.expr(e)).collect::<CResult<Vec<_>>>()?.join(", ");
                Ok(format!("({})", vs))
            }

            Expr::Binary(lhs, op, rhs, _) => {
                let l = self.expr(lhs)?;
                let r = self.expr(rhs)?;
                let op_str = match op {
                    BinOp::Add => "+",  BinOp::Sub => "-",
                    BinOp::Mul => "*",  BinOp::Div => "/",
                    BinOp::Rem => "%",  BinOp::Eq  => "==",
                    BinOp::Ne  => "!=", BinOp::Lt  => "<",
                    BinOp::Le  => "<=", BinOp::Gt  => ">",
                    BinOp::Ge  => ">=", BinOp::And => "&&",
                    BinOp::Or  => "||", BinOp::BitAnd => "&",
                    BinOp::BitOr => "|", BinOp::BitXor => "^",
                    BinOp::Shl => "<<", BinOp::Shr => ">>",
                };
                Ok(format!("({} {} {})", l, op_str, r))
            }

            Expr::Unary(op, e, _) => {
                let v = self.expr(e)?;
                let op_str = match op {
                    UnOp::Neg   => "-",
                    UnOp::Not   => "!",
                    UnOp::Ref   => "&",
                    UnOp::Deref => "*",
                };
                Ok(format!("({}{})", op_str, v))
            }

            Expr::Assign(lhs, op, rhs, _) => {
                let l = self.expr(lhs)?;
                let r = self.expr(rhs)?;
                let op_str = match op {
                    AssignOp::Assign    => "=",
                    AssignOp::AddAssign => "+=",
                    AssignOp::SubAssign => "-=",
                    AssignOp::MulAssign => "*=",
                    AssignOp::DivAssign => "/=",
                };
                Ok(format!("{} {} {}", l, op_str, r))
            }

            Expr::Call(callee, args, _) => {
                let c = self.expr(callee)?;
                let a = args.iter().map(|e| self.expr(e)).collect::<CResult<Vec<_>>>()?.join(", ");
                // map built-in println → println! macro
                match c.as_str() {
                    "println" => {
                        if a.is_empty() { return Ok("println!()".to_string()); }
                        let mut parts = a.splitn(2, ", ");
                        let fmt = parts.next().unwrap_or("\"{}\"");
                        if let Some(rest) = parts.next() {
                            Ok(format!("println!({}, {})", fmt, rest))
                        } else {
                            Ok(format!("println!(\"{{}}\", {})", fmt))
                        }
                    }
                    "print" => {
                        if a.is_empty() { return Ok("print!()".to_string()); }
                        let mut parts = a.splitn(2, ", ");
                        let fmt = parts.next().unwrap_or("\"{}\"");
                        if let Some(rest) = parts.next() {
                            Ok(format!("print!({}, {})", fmt, rest))
                        } else {
                            Ok(format!("print!(\"{{}}\", {})", fmt))
                        }
                    }
                    "assert"    => Ok(format!("assert!({})", a)),
                    "assert_eq" => Ok(format!("assert_eq!({})", a)),
                    "len"       => Ok(format!("{}.len()", a)),
                    "range"     => {
                        let mut it = a.splitn(2, ", ");
                        match (it.next(), it.next()) {
                            (Some(s), Some(e)) => Ok(format!("({s}..{e})") ),
                            (Some(e), None)    => Ok(format!("(0..{e})")),
                            _ => Ok("(0..0)".to_string()),
                        }
                    }
                    _ => Ok(format!("{}({})", c, a)),
                }
            }

            Expr::MethodCall(obj, method, args, _) => {
                let o = self.expr(obj)?;
                let a = args.iter().map(|e| self.expr(e)).collect::<CResult<Vec<_>>>()?.join(", ");
                Ok(format!("{}.{}({})", o, method, a))
            }

            Expr::Field(obj, field, _) => {
                let o = self.expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }

            Expr::Index(arr, idx, _) => {
                let a = self.expr(arr)?;
                let i = self.expr(idx)?;
                Ok(format!("{}[{} as usize]", a, i))
            }

            Expr::StructInit(name, fields, _) => {
                let fs = fields.iter().map(|(n, e)| {
                    Ok(format!("{}: {}", n, self.expr(e)?))
                }).collect::<CResult<Vec<_>>>()?.join(", ");
                Ok(format!("{} {{ {} }}", name, fs))
            }

            Expr::EnumVariant(enum_name, variant, args, _) => {
                if args.is_empty() {
                    Ok(format!("{}::{}", enum_name, variant))
                } else {
                    let a = args.iter().map(|e| self.expr(e)).collect::<CResult<Vec<_>>>()?.join(", ");
                    Ok(format!("{}::{}({})", enum_name, variant, a))
                }
            }

            Expr::If(b) => {
                let cond = self.expr(&b.cond)?;
                let t    = self.expr(&b.then_val)?;
                let el   = self.expr(&b.else_val)?;
                Ok(format!("if {} {{ {} }} else {{ {} }}", cond, t, el))
            }

            Expr::Match(m) => {
                let subj = self.expr(&m.subject)?;
                self.push();
                let arms = m.arms.iter().map(|arm| {
                    let pat  = self.pattern(&arm.pattern);
                    let guard = if let Some(g) = &arm.guard {
                        format!(" if {}", self.expr(g).unwrap_or_default())
                    } else { String::new() };
                    let body = self.expr(&arm.body).unwrap_or_default();
                    format!("{}{}{} => {},", self.ind(), pat, guard, body)
                }).collect::<Vec<_>>().join("\n");
                self.pop();
                Ok(format!("match {} {{\n{}\n{}}}", subj, arms, self.ind()))
            }

            Expr::Block(stmts, tail, _) => {
                self.push();
                let body = stmts.iter().map(|s| self.stmt(s)).collect::<CResult<Vec<_>>>()?.join("\n");
                let tail_part = if let Some(t) = tail {
                    format!("\n{}{}", self.ind(), self.expr(t)?)
                } else { String::new() };
                self.pop();
                Ok(format!("{{\n{}{}\n{}}}", body, tail_part, self.ind()))
            }

            Expr::Range(start, end, inclusive, _) => {
                let s = self.expr(start)?;
                let e = self.expr(end)?;
                if *inclusive { Ok(format!("({}..={})", s, e)) }
                else          { Ok(format!("({}..{})", s, e)) }
            }

            Expr::Closure(params, ret, body, _) => {
                let ps = params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
                let b  = self.expr(body)?;
                Ok(format!("|{}| {}", ps, b))
            }

            Expr::Map(pairs, _) => {
                let items = pairs.iter().map(|(k, v)| {
                    Ok(format!("({}, {})", self.expr(k)?, self.expr(v)?))
                }).collect::<CResult<Vec<_>>>()?.join(", ");
                Ok(format!("[{}].into_iter().collect::<std::collections::HashMap<_,_>>()", items))
            }
        }
    }

    // ── patterns ─────────────────────────────────────────────────────────────

    fn pattern(&self, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard          => "_".to_string(),
            Pattern::Ident(n)          => n.clone(),
            Pattern::Int(n)            => n.to_string(),
            Pattern::Float(f)          => format!("{}_f64", f),
            Pattern::Str(s)            => format!("\"{}\"", s),
            Pattern::Bool(b)           => b.to_string(),
            Pattern::Nil               => "None".to_string(),
            Pattern::Tuple(ps)         => format!("({})", ps.iter().map(|p| self.pattern(p)).collect::<Vec<_>>().join(", ")),
            Pattern::EnumVariant(e, v, ps) => {
                if ps.is_empty() { format!("{}::{}", e, v) }
                else { format!("{}::{}({})", e, v, ps.iter().map(|p| self.pattern(p)).collect::<Vec<_>>().join(", ")) }
            }
            Pattern::Or(ps)            => ps.iter().map(|p| self.pattern(p)).collect::<Vec<_>>().join(" | "),
            Pattern::Struct(n, fs)     => {
                let fields = fs.iter().map(|(k, v)| format!("{}: {}", k, self.pattern(v))).collect::<Vec<_>>().join(", ");
                format!("{} {{ {} }}", n, fields)
            }
        }
    }

    // ── types ─────────────────────────────────────────────────────────────────

    fn type_expr(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Simple(n)           => self.map_type(n),
            TypeExpr::Generic(n, args)    => {
                let a = args.iter().map(|t| self.type_expr(t)).collect::<Vec<_>>().join(", ");
                format!("{}<{}>", self.map_type(n), a)
            }
            TypeExpr::Ref(inner, mutable) => {
                let m = if *mutable { "mut " } else { "" };
                format!("&{}{}", m, self.type_expr(inner))
            }
            TypeExpr::Slice(inner)        => format!("[{}]", self.type_expr(inner)),
            TypeExpr::Array(inner, n)     => format!("[{}; {}]", self.type_expr(inner), n),
            TypeExpr::Tuple(tys)          => {
                let ts = tys.iter().map(|t| self.type_expr(t)).collect::<Vec<_>>().join(", ");
                format!("({})", ts)
            }
            TypeExpr::Fn(params, ret)     => {
                let ps = params.iter().map(|t| self.type_expr(t)).collect::<Vec<_>>().join(", ");
                format!("fn({}) -> {}", ps, self.type_expr(ret))
            }
            TypeExpr::Option(inner)       => format!("Option<{}>", self.type_expr(inner)),
            TypeExpr::Result(ok, err)     => format!("Result<{}, {}>", self.type_expr(ok), self.type_expr(err)),
            TypeExpr::Never               => "!".to_string(),
            TypeExpr::Unit                => "()".to_string(),
            TypeExpr::Infer               => "_".to_string(),
        }
    }

    fn map_type(&self, name: &str) -> String {
        match name {
            "int"    => "i64",
            "float"  => "f64",
            "bool"   => "bool",
            "str"    => "String",
            "string" => "String",
            "char"   => "char",
            "uint"   => "u64",
            "i8"  | "i16"  | "i32"  | "i64"  | "i128"  => name,
            "u8"  | "u16"  | "u32"  | "u64"  | "u128"  => name,
            "f32" | "f64"  => name,
            "usize" | "isize" => name,
            other    => other,
        }.to_string()
    }
}

// ─── Public compile entry point ───────────────────────────────────────────────

/// Compile TRU source code to Rust source code.
pub fn compile_tru(source: &str) -> CResult {
    use crate::tru_lang::parser::Parser;
    let program = Parser::parse(source)
        .map_err(|e| CompileError(e.to_string()))?;
    Compiler::compile(&program)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn check(src: &str) -> String {
        compile_tru(src).expect("compile failed")
    }

    #[test]
    fn test_compile_let() {
        let out = check("let x = 42;");
        assert!(out.contains("let x = 42"));
    }

    #[test]
    fn test_compile_fn() {
        let out = check("fn add(a: int, b: int) -> int { return a + b; }");
        assert!(out.contains("fn add"));
        assert!(out.contains("i64"));
        assert!(out.contains("return"));
    }

    #[test]
    fn test_compile_struct() {
        let out = check("struct Point { x: float, y: float }");
        assert!(out.contains("struct Point"));
        assert!(out.contains("f64"));
    }

    #[test]
    fn test_compile_println() {
        let out = check(r#"println("hello");"#);
        assert!(out.contains("println!"));
    }

    #[test]
    fn test_compile_if() {
        let out = check("if x > 0 { return 1; } else { return 0; }");
        assert!(out.contains("if (x > 0)"));
    }
}
